name: gh
summary: Unofficial Snap package for GitHub-CLI
description: |
  https://cli.github.com
  **`gh` - The GitHub CLI tool**
  `gh` is GitHub on the command line, and it's now available in beta. It brings pull requests, issues, and other GitHub concepts to
  the terminal next to where you are already working with `git` and your code.
  _Usage_
  - `gh pr [status, list, view, checkout, create]`
  - `gh issue [status, list, view, create]`
  - `gh help`
version: git
contact: https://github.com/lengau/gh-snap
issues: https://github.com/lengau/gh-snap/issues
source-code: https://github.com/lengau/gh-snap
website: https://cli.github.com
grade: stable
confinement: classic
base: bare
build-base: core22
license: MIT
architectures:
  - build-on: [ amd64, i386, arm64, armhf ]
    build-for: amd64
  - build-on: [amd64, i386, arm64, armhf]
    build-for: i386
  - build-on: [ amd64, i386, arm64, armhf ]
    build-for: arm64
  - build-on: [amd64, i386, arm64, armhf]
    build-for: armhf

parts:
  bin:
    plugin: dump
    source:
      - to i386: https://github.com/cli/cli/releases/download/v2.20.0/gh_2.20.0_linux_386.tar.gz
      - to amd64: https://github.com/cli/cli/releases/download/v2.20.0/gh_2.20.0_linux_amd64.tar.gz
      - to arm64: https://github.com/cli/cli/releases/download/v2.20.0/gh_2.20.0_linux_arm64.tar.gz
      - to armhf: https://github.com/cli/cli/releases/download/v2.20.0/gh_2.20.0_linux_armv6.tar.gz
    # endsources
    source-type: tar
    stage:
      - bin/gh
      - LICENSE
  completion:
    plugin: dump
    source: .
    source-type: local
    stage:
      - completion.sh
apps:
  gh:
    command: bin/gh
    completer: completion.sh
