name: Release on a tag

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      tag_name:
        description: "The tag to release"
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.tag_name || github.ref_name }}
      - uses: snapcore/action-build@v1
        id: snapcraft
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.snapcraft.outputs.snap }}


