name: Sync new releases

on:
  workflow_dispatch:  # Allow manual run
  schedule:
    - cron: "0 6 * * *"  # Every day at 06:00 UTC

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  get_releases:
    runs-on: ubuntu-latest
    outputs:
      releases: ${{ steps.releases.outputs.RELEASES }}
    steps:
      - name: Determine releases to package
        id: releases
        run: |
          get_releases() { gh api "repos/${1}/releases?per_page=${2}&page=2" -q '.[].tag_name' | tac; }
          check_release_tag() { gh api "repos/${1}/releases/tags/${2}" >> /dev/null 2>&1; }
          get_unmatched_releases() {
            for release in $(get_releases ${1} ${2})
            do
              if ! check_release_tag ${3} $release
              then
                echo -n "${release} "
              fi
            done
          }
          
          export RELEASES="'$(get_unmatched_releases $UPSTREAM $CHECK_N $GITHUB_REPOSITORY)'"
          echo "RELEASES=$RELEASES" | tee $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}
          UPSTREAM: cli/cli
          CHECK_N: 5
  commit_and_tag:
    needs: get_releases
    strategy:
      runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Commit releases
      run: |
        git fetch --force --tags
        git config user.name 'Release Action'
        git config user.email 'gh-snap-release-action@actions.github.com'
        for release in ${{needs.get_releases.outputs.releases}}
        do
          $(gh api repos/cli/cli/releases/tags/${release} -q '.assets.[].browser_download_url|match(".*linux_([a-z0-9]*).tar.gz") | "export ARCH_" + .captures[0].string + "=" + .string' | sed s/386/i386/)
          sed -i 's/^\(version: \).*$/\1'"${release}"'/' snap/snapcraft.yaml
          sed -i -e 's!^\(\s*- on amd64: \).*$!\1'"${ARCH_amd64}"'!' -e 's!^\(\s*- on i386: \).*$!\1'"${ARCH_i386}"'!' -e 's!^\(\s*- on armhf: \).*$!\1'"${ARCH_armv6}"'!' -e 's!^\(\s*- on arm64: \).*$!\1'"${ARCH_arm64}"'!' snap/snapcraft.yaml
          git add snap/snapcraft.yml
          wget -O - $ARCH_amd64 | tar zx --wildcards "*bin/gh" -O > gh
          chmod +x gh
          ./gh completion -s bash > completion.sh
          rm gh
          git add completion.sh
          git commit -m "Release version ${release}"
          git tag -f ${release}
        done
        git push --tags
