name: Snap upstream releases

on:
  workflow_dispatch:  # Allow manual run
  schedule:
    - cron: "0 6 * * *"  # Every day at 06:00 UTC

concurrency: ${{ github.workflow }}

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  sync-gh-releases:
    uses: lengau/snappify/.github/workflows/sync-gh-releases.yaml@v0.0.2
    with:
      upstream_repository: cli/cli
      prep_script: tools/prep_release.sh
  do_releases:
    runs-on: ubuntu-latest
    needs: sync-gh-releases
    if: ${{ needs.sync-gh-releases.outputs.release_tags != '[]' && needs.sync-gh-releases.outputs.services != '' }}
    strategy:
      max-parallel: 1
      matrix:
        tag: ${{ fromJSON(needs.sync-gh-releases.outputs.release_tags) }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.tag }}
      - uses: snapcore/action-build@v1
        id: snapcraft
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: GitHub CLI ${{ matrix.tag }}
          body: See upstream release at https://github.com/cli/cli/releases/tag/${{ matrix.tag }}
          prerelease: ${{ contains(matrix.tag, 'pre') }}
          tag_name: ${{ matrix.tag }}
          files: "*.snap"
